import { FeatureFlag } from "src/featureflag/featureflag.service";

export const FuseFlag = {
    DashboardGrossProductionWidgetMvp: { key: "release-dashboard-gross-production-widget-mvp", defaultValue: false } as FeatureFlag<boolean>,
    DashboardPendingClaimsWidgetMvp: { key: "release-dashboard-pending-claims-widget-mvp", defaultValue: false } as FeatureFlag<boolean>,
    DashboardNetProductionWidgetMvp: { key: "release-dashboard-net-production-widget-mvp", defaultValue: false } as FeatureFlag<boolean>,
    DashboardClinicalNotesWidgetMvp: { key: "release-open-clinical-notes-dashboard-widget-mvp", defaultValue: false } as FeatureFlag<boolean>,
    DashboardInsuranceClaimsWidgetMvp: { key: "release-insurance-claims-dashboard-widget-mvp", defaultValue: false } as FeatureFlag<boolean>,
    DashboardReceivablesWidgetMvp: { key: "release-receivables-dashboard-widget-mvp", defaultValue: false } as FeatureFlag<boolean>,
    DashboardAppointmentWidgetMvp: { key: "release-appointment-dashboard-widget-mvp", defaultValue: false } as FeatureFlag<boolean>,
    DashboardScheduleUtilizationWidgetMvp: { key: "release-schedule-utilization-dashboard-widget-mvp", defaultValue: false } as FeatureFlag<boolean>,
    ReportReceivablesByProvider: { key: "release-receivables-by-provider-report", defaultValue: false } as FeatureFlag<boolean>,
    UsePaymentService: { key: "release-payment-management-service", defaultValue: false } as FeatureFlag<boolean>,
    EClaimSubmissionDisabledMessage: { key: "configure-eclaim-submission-disabled-message", defaultValue: "" } as FeatureFlag<string>,
    ReportPatientsByBenefitPlan: { key: "release-patients-by-benefit-plan-report", defaultValue: false } as FeatureFlag<boolean>,
    AllowRealTimeEligibilityVerification: { key: "allow-real-time-eligibility-verification", defaultValue: true } as FeatureFlag<boolean>,
    ConfigureRealTimeEligibilityDisabledMessage: { key: "configure-real-time-eligibility-disabled-message", defaultValue: "" } as FeatureFlag<string>,
    ReportServiceCodeByServiceTypeProductivity: { key: "release-service-code-by-service-type-productivity-report", defaultValue: false } as FeatureFlag<boolean>,
    AllowClaimAttachments: { key: "allow-claim-attachments", defaultValue: true },
    ConfigureClaimAttachmentsDisabledMessage: { key: "configure-claim-attachments-disabled-message", defaultValue: "" },
    AllowVendorEligibilityCheckForAttachmentDialog: { key: "allow-vendor-eligibility-check-for-attachment-dialog", defaultValue: true } as FeatureFlag<boolean>,
    EnableClaimStatusHistory: { key: "enable-claim-status-history", defaultValue: false } as FeatureFlag<boolean>,
    ShowPatientReferrals: { key: "release-referral-managemnt-create-referral", defaultValue: false } as FeatureFlag<boolean>,
    ShowPatientReferralsOnClinical: { key: "release-referral-management-clinical-referral", defaultValue: false } as FeatureFlag<boolean>,
    ShowPatientOverview: { key: "release-patient-overview", defaultValue: false } as FeatureFlag<boolean>,
    ShowScheduleV2: { key: "release-schedule-new-ui-enabled", defaultValue: false } as FeatureFlag<boolean>,
    ShowScheduleV2Alt: { key: "release-schedule-new-ui-alternate-enabled", defaultValue: false } as FeatureFlag<boolean>,
    ShowLegacySchedule: { key: "release-schedule-legacy-ui-enabled", defaultValue: false } as FeatureFlag<boolean>,
    DisableStatusIconOnAppointmentCard: { key: "release-disable-status-icon-onappointment-card", defaultValue: false } as FeatureFlag<boolean>,
    ReferredPatientsReport: { key: "release-referred-patients-report", defaultValue: false } as FeatureFlag<boolean>,
    ReferredPatientsReportFilter: { key: "release-referral-patients", defaultValue: false } as FeatureFlag<boolean>,
    ReportDaySheet: { key: "release-day-sheet-report", defaultValue: false } as FeatureFlag<boolean>,
    ReportDaySheetPdf: { key: "release-day-sheet-pdf-report", defaultValue: false } as FeatureFlag<boolean>,
    NegativeAdjustmentsWidget: { key: "release-negative-adjustments-widget", defaultValue: false } as FeatureFlag<boolean>,
    PositiveAdjustmentsWidget: { key: "release-positive-adjustments-widget", defaultValue: false } as FeatureFlag<boolean>,
    GrossProductionWidget: { key: "release-gross-production-widget", defaultValue: false } as FeatureFlag<boolean>,
    CollectionToNetProductionWidget: { key: "release-collection-to-net-production-widget", defaultValue: false } as FeatureFlag<boolean>,
    EnableNewEraIngestion: { key: "configure-enable-fuse-era-ingest", defaultValue: false } as FeatureFlag<boolean>,
    EnableNewStatementsExperience: { key: "release-new-statements-experience", defaultValue: false } as FeatureFlag<boolean>,
    ShowInsuranceUIErrors: { key: "show-insurance-ui-errors", defaultValue: false } as FeatureFlag<boolean>,
    // BoolFlag: { key: "ui.testonly.bool", defaultValue: false } as FeatureFlag<boolean>,
    // NumberFlag: { key: "ui.testonly.number", defaultValue: 0 } as FeatureFlag<number>,
    // JsonObjectFlag: { key: "ui.testonly.jsonobject", defaultValue: {variation: 5, description: "default"}} as FeatureFlag<object>,
    // JsonArrayFlag: { key: "ui.testonly.jsonarray", defaultValue: [5,5,5]} as FeatureFlag<number[]>
    DashboardReferralsWidgetMvp: { key: "release-dashboard-referrals-widget-mvp", defaultValue: false } as FeatureFlag<boolean>,
    ReleseOldReferral: { key: "release-hide-patient-profile-referral", defaultValue: false } as FeatureFlag<boolean>,
    EnableChartColorsCache: { key: "release-chart-colors-cache", defaultValue: true } as FeatureFlag<boolean>,
    AddNarlugaLinkInQuickLinksSection: { key: "release-add-narluga-link-in-quick-links-section", defaultValue: true } as FeatureFlag<boolean>,
    viewAddEditCarriersNewUi: { key: "release-view-add-edit-carriers-new-ui", defaultValue: false } as FeatureFlag<boolean>,
    EnableOrthodonticContracts: { key: "release-orthodontic-contracts", defaultValue: false } as FeatureFlag<boolean>,    
    AutoApplyPartnerPaymentsIsEnabled: { key: 'release-auto-apply-partner-payments', defaultValue: false } as FeatureFlag<boolean>,
    ShowHelp: { key: "release-help-page-mfe", defaultValue: false } as FeatureFlag<boolean>,
    EnableFullstoryDataCollection: { key: "enable-fullstory-data-collection", defaultValue: false } as FeatureFlag<boolean>,
    PatientCommunicationCenterReferral: { key: "release-patient-communication-center-referral", defaultValue: false } as FeatureFlag<boolean>,
    ReportProductionByProvider: { key: "release-production-by-provider-report", defaultValue: false } as FeatureFlag<boolean>,
    CreateApptColorProvColorToggle: { key: "release-create-appt-color-prov-color-toggle", defaultValue: false } as FeatureFlag<boolean>,
    ApteryxUseLocal: { key: "release-apteryx-use-local", defaultValue: false } as FeatureFlag<boolean>,
    // SAPI to Practice API migration flags
    UsePracticeApiForConditions: { key: "release-practices-api-migration-conditions", defaultValue: false } as FeatureFlag<boolean>,
    UsePracticeApiForPreventiveServiceTypes: { key: "release-practices-api-migration-preventiveservicetypes", defaultValue: false } as FeatureFlag<boolean>,
    ShowNotifications: { key: "release-notifications", defaultValue: false } as FeatureFlag<boolean>,
    ApteryxDevEnvironment: { key: "config-xv-web-developer-environment", defaultValue: "false" } as FeatureFlag<string>,
    ReleseEnableReferralNewPatientSection: { key: "release-enable-referral-new-patient-section", defaultValue: false } as FeatureFlag<boolean>,
    EnablePayerIdCorrection: { key: "release-full-practice-payer-id-validation", defaultValue: false } as FeatureFlag<boolean>,
    ShowProviderGoals: { key: "release-show-provider-goals", defaultValue: false } as FeatureFlag<boolean>,
    IncreaseTimeout: { key: "release-increase-timeout", defaultValue: false } as FeatureFlag<boolean>,
    // End of SAPI to Practice API migration flags
    EnableClinicalMedHxV2Navigation: { key: "release-clinical-v-2-medical-history", defaultValue: false } as FeatureFlag<boolean>,
    EnableUpdateAllowedAmountOnPaymentScreen: { key: "release-update-allowed-amounts-on-payment-screens", defaultValue: false } as FeatureFlag<boolean>,
    EnableNotificationsForGrossPerformanceByProviderReport: { key: "release-enable-gross-performance-report-notification", defaultValue: true } as FeatureFlag<boolean>,
    EnableNotificationsForServiceHistoryReport: { key: "release-enable-service-history-report-notification", defaultValue: false } as FeatureFlag<boolean>,
      
    EnableNotificationsForActivityLogsReport: { key: "release-enable-activity-logs-report-notification", defaultValue: false } as FeatureFlag<boolean>,
    EnableNotificationsForUnAssignedUnAppliedCreditsReport: { key: "release-unassigned-unapplied-credits-report-notification", defaultValue: false } as FeatureFlag<boolean>,

    
    EnableNotificationsForCollectionByProviderReport: { key: "release-enable-collection-by-provider-report-notification", defaultValue: false } as FeatureFlag<boolean>,

    EnableMFAPracticeSettings: { key:"release-enable-mfa-practice-settings", defaultValue: false }  as FeatureFlag<boolean>,
    EnableLocumTenensDentist: { key: "release-enable-locum-tenens-dentist", defaultValue: false } as FeatureFlag<boolean>,
    
    EnableEditProfileMFEPage: { key:"edit-person-profile-page", defaultValue: false }  as FeatureFlag<boolean>,
    ReleaseReportInconsistencies: { key: "release-report-inconsistencies", defaultValue: false } as FeatureFlag<boolean>,
    EnableEliminateStaleClaims: { key: "release-eliminate-stale-claims", defaultValue: false } as FeatureFlag<boolean>,
    ShowProviderGoalReport: { key: "release-provider-goal-report", defaultValue: false } as FeatureFlag<boolean>,
    ReleaseReferralExport: { key: "release-referral-export", defaultValue: false } as FeatureFlag<boolean>,

} as const;
